### ISSUE TITLE
FASTA sequence with any line returns is rejected

### ISSUE THREAD

**Issue by StevenCannon-USDA** [LegumeFederation/tripal_blast#6]
I am often getting this message, for what is formally valid fasta sequence:
“You need to provide a valid amino acid residues FASTA sequence for the query.”

The trigger appears to be line returns (even a single return at the end of a single sequence). I see the problem with both nucleotide and protein BLAST, at both legumeinfo.org and PeanutBase.org.

Testing results:

https://legumeinfo.org/blast/protein/protein 
blastp against Vigna radiata - proteins

https://peanutbase.org/blast/protein/protein
blastp against Arachis duranensis - proteins

=== WORKS (if no terminal line return):
>Glyma.02g227200.1 fatty acid desaturase 8
MVKDTKPLAYAANNGYQQKGSSFDFDPSAPPPFKIAEIRASIPKHCWVKNPWRSLSYVLRDVLVIAALVAAAIHFDNWLLWLIYCPIQGTMFWALFVLGHDCGHGSFSDSPLLNSLVGHILHSSILVPYHGWRISHRTHHQNHGHIEKDESWVPLTEKIYKNLDSMTRLIRFTVPFPLFVYPIYLFSRSPGKEGSHFNPYSNLFPPSERKGIAISTLCWATMFSLLIYLSFITSPLLVLKLYGIPYWIFVMWLDFVTYLHHHGHHQKLPWYRGKEWSYLRGGLTTVDRDYGWINNIHHDIGTHVIHHLFPQIPHYHLVEATQAAKPVLGDYYREPERSAPLPFHLIKYLIQSMRQDHFVSDTGDVVYYQTDSLLLHSQRD

=== FAILS:
>Glyma.02g227200.1 fatty acid desaturase 8
MVKDTKPLAYAANNGYQQKGSSFDFDPSAPPPFKIAEIRASIPKHCWVKNPWRSLSYVLRDVLVIAALVAAA
IHFDNWLLWLIYCPIQGTMFWALFVLGHDCGHGSFSDSPLLNSLVGHILHSSILVPYHGWRISHRTHHQNHG
HIEKDESWVPLTEKIYKNLDSMTRLIRFTVPFPLFVYPIYLFSRSPGKEGSHFNPYSNLFPPSERKGIAIST
LCWATMFSLLIYLSFITSPLLVLKLYGIPYWIFVMWLDFVTYLHHHGHHQKLPWYRGKEWSYLRGGLTTVDR
DYGWINNIHHDIGTHVIHHLFPQIPHYHLVEATQAAKPVLGDYYREPERSAPLPFHLIKYLIQSMRQDHFVS
DTGDVVYYQTDSLLLHSQRD

=== WORKS (if no terminal line return):
>NBS_CC 
erpsestiVGletmleklwnrLledndvgivgiyGMGGVGKTTLatqifNdfdvkgehFdrviWVvVSkefnvekiqqdIlekLglgdeewlekteeekaaeienLfqlLegKkfLLvLDDvWekevdLdkigvpfPdrenGsKvlfTTRsesvavcgdmgvdxmevecLtpeeAWeLFqkkvfentlksdpeieelaKevvkkCgGLPLAlkVlGgllacKrtvqEWkraievlssslaaefsgmessilpvLklSYdnLppelKsCFLYcalFPEDykIekekLieyWiaEGfideseggetaedvGyeylgeLVrrsLleegdktdnetsrketVkMHDvvREmALwiaseegfkeviiVraGvglreipnvkswntvrRmSlmnneieelldspenpklrsLltlllqsnsh

=== FAILS (if there IS a terminal line return):
>NBS_CC 
ERPSESTIVGLETMLEKLWNRLLEDNDVGIVGIYGMGGVGKTTLATQIFNDFDVKGEHFDRVIWVVVSKEFNVEKIQQDILEKLGLGDEEWLEKTEEEKAAEIENLFQLLEGKKFLLVLDDVWEKEVDLDKIGVPFPDRENGSKVLFTTRSESVAVCGDMGVDXMEVECLTPEEAWELFQKKVFENTLKSDPEIEELAKEVVKKCGGLPLALKVLGGLLACKRTVQEWKRAIEVLSSSLAAEFSGMESSILPVLKLSYDNLPPELKSCFLYCALFPEDYKIEKEKLIEYWIAEGFIDESEGGETAEDVGYEYLGELVRRSLLEEGDKTDNETSRKETVKMHDVVREMALWIASEEGFKEVIIVRAGVGLREIPNVKSWNTVRRMSLMNNEIEELLDSPENPKLRSLLTLLLQSNSH

**Comment by ekcannon** [comment]
RegEx fixed in validate_fasta_sequence() - api/blast_ui.api.inc.
